name: Napaka v delovanju
description: Napišite poročilo o napaki v delovanju.
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Hvala, ker ste si vzeli čas za izpolnjevanje tega poročila!
  - type: textarea
    id: description
    attributes:
      label: Opis napake
      description: Čim bolj podrobno opišite napako, ki ste jo opazili.
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operacijski sistem
      description: V katerem operacijskem sistemu se pojavlja ta napaka (po možnosti z verzijo)?
      placeholder: npr. Android 14, iOS 17.6, Windows 11, itd.
    validations:
      required: true
  - type: input
    id: browser
    attributes:
      label: Brskalnik
      description: V katerem brskalniku se pojavlja ta napaka (po možnosti z verzijo)?
      placeholder: npr. Chrome 128, Firefox 130, Safari 17.6, itd.
    validations:
      required: true
  - type: textarea
    id: screenshot
    attributes:
      label: Posnetek zaslona
      description: V primeru, da imate vizualne napake, lahko tu prilepite svoj posnetek zaslona.
      placeholder: Kliknite v to besedilno polje in prilepite svoj posnetek zaslona.
    validations:
      required: false
