name: Prošnja za funkcijo
description: Napišite predlog za izboljšavo obstoječih funkcij ali dodajanja novih.
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: Hvala, ker ste si vzeli čas za izpolnjevanje tega poročila!
  - type: textarea
    id: description
    attributes:
      label: Vaša zamisel
      description: V nekaj stavkih opišite svojo zamisel.
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Rešen problem
      description: Kakšen problem bi rešila vaša zamisel?
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Več informacij
      description: Kako bi izgledala vaša zamisel? Kako to rešujejo druge aplikacije?
    validations:
      required: false
