# We have to use the node-modules linker as Yarn PnP does not work with Vite when using different drives
# See: https://github.com/vitejs/vite/issues/10802
# See: https://github.com/vitejs/vite/issues/15496
nodeLinker: node-modules
nmMode: hardlinks-global
