[tool.poetry]
name = "gimvicurnik"
description = "An API for a school timetable, substitutions and menus at Gimnazija Vič"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.0.0"

homepage = "https://gimvicurnik.filips.si/"
repository = "https://github.com/filips123/GimVicUrnik"
documentation = "https://github.com/filips123/GimVicUrnik/blob/main/README.md"

authors = [
    "filips123 <projects@filips.si>",
    "ChristofferNorgaard"
]

keywords = [
    "timetables",
    "substitutions",
    "menus",
    "gimvic"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Database",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
gimvicurnik = "gimvicurnik.__main__:main"

# TODO: Replace pdf2docx with PyMuPDF/pdfplumber/pdfminer
[tool.poetry.dependencies]
python = "^3.8"
PyYAML = "^6.0.0"
Flask = "^2.1.2"
click = "^8.1.3"
schema = "^0.7.5"
requests = "^2.28.1"
SQLAlchemy = "^1.4.39"
pdf2docx = "=0.4.6"
openpyxl = "^3.0.10"
icalendar = "^4.1.0"
beautifulsoup4 = { extras = ["lxml"], version = "^4.11.1" }

# Optional support for Sentry integration
sentry-sdk = { extras = ["flask", "sqlalchemy"], version = "^1.6.0", optional = true }

# Optional support for different databases
PyMySQL = { version = "^1.0.2", optional = true }
mysqlclient = { version = "^2.1.1", optional = true }
psycopg2 = { version = "^2.9.3", optional = true }

[tool.poetry.dev-dependencies]
flakeheaven = "2.0.0"
black = "^22.6.0"
flake8-black = "^0.3.3"
flake8-bugbear = "^22.7.1"

[tool.poetry.extras]
sentry = ["sentry-sdk"]
mysql-py = ["PyMySQL"]
mysql-c = ["mysqlclient"]
pgsql = ["psycopg2"]

[tool.flakeheaven]
max_line_length = 130
format = "grouped"

[tool.flakeheaven.plugins]
"flake8-black" = ["+*"]
"flake8-bugbear" = ["+*"]
"mccabe" = ["+*"]
"pycodestyle" = ["+*", "-E203", "-W503"]
"pyflakes" = ["+*", "-F401"]

[tool.black]
line-length = 130

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
