[tool.poetry]
name = "gimvicurnik"
description = "An API for a school timetable, substitutions and menus at Gimnazija Vič"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.0.0"

homepage = "https://gimvicurnik.filips.si/"
repository = "https://github.com/filips123/GimVicUrnik"
documentation = "https://github.com/filips123/GimVicUrnik/blob/main/README.md"

authors = [
    "filips123 <projects@filips.si>",
    "ChristofferNorgaard"
]

keywords = [
    "timetables",
    "substitutions",
    "menus",
    "gimvic"
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Database",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
gimvicurnik = "gimvicurnik.__main__:main"

[tool.poetry.dependencies]
python = "^3.6.2"
PyYAML = "^5.4.1"
PyMuPDF = "=1.18.19"
Flask = "^2.0.3"
click = "^8.0.4"
schema = "^0.7.5"
requests = "^2.27.1"
SQLAlchemy = "^1.4.31"
pdf2docx = "=0.4.6"
openpyxl = "^3.0.9"
icalendar = "^4.0.9"
beautifulsoup4 = { extras = ["lxml"], version = "^4.10.0" }

# Optional support for Sentry integration
sentry-sdk = { extras = ["flask", "sqlalchemy"], version = "^1.5.5", optional = true }

# Optional support for different databases
PyMySQL = { version = "^1.0.2", optional = true }
psycopg2 = { version = "^2.9.3", optional = true }

[tool.poetry.dev-dependencies]
flakeheaven = "^0.11.1"
black = "^22.1.0"
flake8-black = "^0.2.4"
flake8-bugbear = "^21.11.29"

[tool.poetry.extras]
sentry = ["sentry-sdk"]
mysql = ["PyMySQL"]
pgsql = ["psycopg2"]

[tool.flakehell]
max_line_length = 130
format = "grouped"

[tool.flakehell.plugins]
"flake8-black" = ["+*"]
"flake8-bugbear" = ["+*"]
"mccabe" = ["+*"]
"pycodestyle" = ["+*", "-E203", "-E501", "-E722", "-W503"]
"pyflakes" = ["+*", "-F401"]

[tool.black]
line-length = 130

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
