[tool.poetry]
name = "gimvicurnik"
description = "An API for a school timetable, substitutions and menus at Gimnazija Vič"
readme = "README.md"
license = "GPL-3.0-or-later"
version = "0.0.0"

homepage = "https://gimvicurnik.filips.si/"
repository = "https://github.com/filips123/GimVicUrnik"
documentation = "https://github.com/filips123/GimVicUrnik/blob/main/README.md"

authors = [
    "filips123 <projects@filips.si>",
    "ChristofferNorgaard"
]

keywords = [
    "timetables",
    "substitutions",
    "menus",
    "gimvic"
]

classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Web Environment",
    "Framework :: Flask",
    "Intended Audience :: End Users/Desktop",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Programming Language :: Python :: 3",
    "Topic :: Database",
    "Topic :: Internet :: WWW/HTTP",
    "Topic :: Utilities"
]

[tool.poetry.scripts]
gimvicurnik = "gimvicurnik.__main__:main"

[tool.poetry.dependencies]
python = "^3.6"
PyYAML = "^5.4.1"
Flask = "^1.1.2"
click = "^7.1.2"
schema = "^0.7.4"
requests = "^2.25.1"
SQLAlchemy = "^1.4.7"
pdf2docx = "^0.4.6"
openpyxl = "^3.0.7"
beautifulsoup4 = { extras = ["lxml"], version = "^4.9.3" }
sentry-sdk = { extras = ["flask", "sqlalchemy"], version = "^1.0.0", optional = true }

[tool.poetry.dev-dependencies]
flakehell = "^0.9.0"
black = "^20.8b1"
flake8-black = "^0.2.1"
flake8-bugbear = "^21.4.3"

[tool.poetry.extras]
sentry = ["sentry-sdk"]

[tool.flakehell]
max_line_length = 130
format = "grouped"

[tool.flakehell.plugins]
"flake8-black" = ["+*"]
"flake8-bugbear" = ["+*"]
"mccabe" = ["+*"]
"pycodestyle" = ["+*", "-E203", "-E501", "-E722", "-W503"]
"pyflakes" = ["+*", "-F401"]

[tool.black]
line-length = 130

[tool.poetry-dynamic-versioning]
enable = true

[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry.core.masonry.api"
