name: Check Frontend

on:
  push:
    paths:
      - .github/workflows/website.yaml
      - website/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/website.yaml
      - website/**

defaults:
  run:
    working-directory: website
    shell: bash

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            ~/.yarn/berry/cache
            ./node_modules/.cache
            ./node_modules/.vite
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-lint-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Copy configuration
        run: cp .env.sample .env

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint the project with ESLint
        if: always()
        run: yarn lint

      - name: Lint the project with Prettier
        if: always()
        run: yarn format

  typecheck:
    name: Typechecking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            ~/.yarn/berry/cache
            ./node_modules/.cache
            ./node_modules/.vite
          key: ${{ runner.os }}-yarn-typecheck-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-typecheck-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Copy configuration
        run: cp .env.sample .env

      - name: Install dependencies
        run: yarn install --immutable

      - name: Typecheck the project
        run: yarn typecheck

  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack
        run: corepack enable

      - name: Configure Yarn cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/yarn
            ~/.yarn/berry/cache
            ./node_modules/.cache
            ./node_modules/.vite
          key: ${{ runner.os }}-yarn-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-build-

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Copy configuration
        run: cp .env.sample .env

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build the project
        run: yarn build
