name: Check Frontend

on:
  push:
    paths:
      - .github/workflows/website.yaml
      - website/**
    branches:
      - main
  pull_request:
    paths:
      - .github/workflows/website.yaml
      - website/**

defaults:
  run:
    working-directory: website
    shell: bash

jobs:
  lint:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            ./node_modules/.cache
            ./node_modules/.vite
          key: ${{ runner.os }}-yarn-lint-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-lint-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Copy configuration
        run: cp .env.sample .env

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint the project
        run: yarn lint

  build:
    name: Building
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            ./node_modules/.cache
            ./node_modules/.vite
          key: ${{ runner.os }}-yarn-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-build-

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Copy configuration
        run: cp .env.sample .env

      - name: Install dependencies
        run: yarn install

      - name: Build the project
        run: yarn build
